### Create a new customer
POST http://localhost:9001/api/v1/customers
Content-Type: application/json

{
  "name": "Anna",
  "address": "New York"
}

### GET custoimer by id
GET http://localhost:9001/api/v1/customers/61
Content-Type: application/json

### Update customer name
PATCH http://localhost:9001/api/v1/customers/61
Content-Type: application/json-patch+json

{
  "path": "/name",
  "op": "replace",
  "value": "Evgeniy2"
}

### Update customer address
PATCH http://localhost:9001/api/v1/customers/61
Content-Type: application/json-patch+json

{
  "path": "/address",
  "op": "replace",
  "value": "London"
}

### Delete a customer by ID
DELETE http://localhost:9001/api/v1/customers/60
Content-Type: application/json-patch+json

### Actuator producer
GET http://localhost:9001/actuator/health

### Actuator consumer
GET http://localhost:9002/actuator/health
