server:
  port: 9002

spring:
  application:
   name: consumer-service
  data:
    mongodb:
      database: events
      uri: mongodb://admin:password@localhost:27017/admin?authSource=admin
      authentication-database: admin
  kafka:
    bootstrap-servers: http://localhost:19092,http://localhost:29092
    consumer:
      group-id: customersConsumer
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema:
          registry:
            url: http://localhost:8081
        specific:
          avro:
            reader: true
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: http://localhost:8081
  jpa:
    open-in-view: false
kafka:
  topics:
    create-customer-event:
      name: CreateCustomerEventTopic
      partitions: 1
      replicationFactor: 2
    customer-view-event:
      name: CustomerViewEventTopic
      partitions: 1
      replicationFactor: 2
    update-customer-name-event:
      name: UpdateCustomerNameEventTopic
      partitions: 1
      replicationFactor: 2
    update-customer-address-event:
      name: UpdateCustomerAddressEventTopic
      partitions: 1
      replicationFactor: 2
    delete-customer-event:
      name: DeleteCustomerEventTopic
      partitions: 1
      replicationFactor: 2

logging:
  config: /home/anduser/dev/assessment/assessment-m2/consumer/src/main/resources/logback.xml
